name: Android Common Workflow

on:
  workflow_call:
    inputs:
      runTests:
        required: false
        type: boolean
        default: true
      buildRelease:
        required: false
        type: boolean
        default: false
      uploadArtifacts:
        required: false
        type: boolean
        default: false

jobs:
  android:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b #v4.6.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 #v3.2.2

    - name: Run tests with Gradle
      if: ${{ inputs.runTests }}
      run: ./gradlew testDebugUnitTest

    - name: Upload Unit Test Report
      if: ${{ inputs.runTests }}
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b #v4.5.0
      with:
        name: unit-test-report
        path: app/build/reports/tests/testDebugUnitTest/

    - name: Decode Keystore
      if: ${{ inputs.buildRelease }}
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > keystore.jks

    - name: Build Release apk
      if: ${{ inputs.buildRelease }}
      env:
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace

    - name: Build Release bundle
      if: ${{ inputs.buildRelease }}
      env:
        RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      run: ./gradlew bundleRelease --stacktrace

    - name: Upload Release Build to Artifacts
      if: ${{ inputs.uploadArtifacts }}
      uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 #v3.2.1
      with:
        name: release-artifacts
        path: app/build/outputs/apk/release/*.apk
