name: Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/android-common.yaml
    with:
      runTests: true
      buildRelease: false
      uploadArtifacts: false
